Support/wagtail 50
torchbox-forks/wagtail-headless-preview pull request #1
Opened 2023-10-04 12:15 UTC by lparsons396

- Support Wagtail 5.1

2023-10-04 14:04 UTC, zerolab commented on tox.ini
> +    py{38,39,310}-django{3.2,4.1}-wagtail{4.1,4.2,5.0,5.1}
since we only support LTS and the last 2 non-LTS releases, 4.2 should drop from the list
https://endoflife.date/wagtail

2023-10-04 14:05 UTC, zerolab commented on CHANGELOG.md
> +- Add Wagtail 5.1 support
```suggestion
- Make Wagtail 5.1 support official
```

2023-10-06 12:37 UTC, lparsons396 commented on tox.ini
> +    py{38,39,310}-django{3.2,4.1}-wagtail{4.1,4.2,5.0,5.1}
Gotcha, thanks for pointing me in the direction of [endoflife](https://endoflife.date/wagtail) too

2023-10-06 13:33 UTC, zerolab requested changes

2023-10-06 13:33 UTC, zerolab commented on tox.ini
> +    py{38,39,310}-django{3.2,4.1}-wagtail{4.2,5.0,5.1}
Wagtail 4.1 is the LTS version. 4.2 is the one that needs dropping

2023-10-19 18:23 UTC, zerolab commented
@lparsons396 soo... I just noticed this PR is against torchbox-forks, rather than the actual repository 🙈 

It would be great if you could open the PR against https://github.com/torchbox/wagtail-headless-preview as that is where it belongs ;)

2023-10-24 09:28 UTC, nickmoreton approved these changes
@lparsons396 Looks good, I approve.

2023-10-24 13:35 UTC, zerolab commented
https://github.com/torchbox/wagtail-headless-preview/pull/50 was already merged.

In the future, for our repos (i.e. in https://github.com/torchbox/) can we please always open a PR against the main repo rather than on the fork

2023-10-24 15:11 UTC, nickmoreton commented
> [torchbox#50](https://github.com/torchbox/wagtail-headless-preview/pull/50) was already merged.
> 
> In the future, for our repos (i.e. in https://github.com/torchbox/) can we please always open a PR against the main repo rather than on the fork

Thanks @zerolab it makes sense. I'll need to communicate that somehow, are you likely to code review them or could it be someone else?

2023-10-24 15:25 UTC, zerolab commented
It helps having someone else do a code review, but it is the maintainer's job to do a final one

2025-03-05 12:44 UTC, nickmoreton commented
Closing: no longer required

2025-03-05 12:44 UTC, closed without merging